[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 1

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 2

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 3

